In [1]:
import numpy as np    ###in numpy num stands for numerical & py for python
                      ###np is the Alias of numpy (short_form of numpy that will be used)

In [4]:
arr=np.array([1,2,3])   #Creating array using numpy
print(arr)              #Square brackets are uses for INDEXING, SLICING, and LIST o/t paranthesis() is used

[1 2 3]


In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,10)  #note here ARANGE is used and NOT arrange
#output will not include 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(20) #20 not included
#starting number not provided so the DEFAULT STARTING NUMBER IS 0
#DEFAULT STEP SIZE =1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
#To get HELP BOX for any function use the shortcut key (shift + tab) 

In [11]:
np.zeros(10) 
#output is FLOAT by default

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#to get integers
print(np.zeros(5,dtype=int))
print(np.zeros(6,int))

[0 0 0 0 0]
[0 0 0 0 0 0]


In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2,5))
#2 ROWS
#5 COLUMNS
#data type is FLOAT be default

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.linspace(0,1,4)
#DIVIDES the interval b/w (0,1) into 4 equal parts.
#(start,end(the end is included,here 1 is included,no. of divisions))

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [24]:
np.linspace(0,20,8)
#linspace means LINEALRLY(that is equally) SPACED

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [25]:
np.linspace(0,1)
#when spacing is not specified the DEFAULT spacing is 50

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [28]:
np.eye(5,dtype=int)
#Identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.random.rand(3,2)
#random floatig numbers that are less than 1 will come in 3ROW AND 2 COLUMN

array([[0.06949632, 0.84417012],
       [0.54882982, 0.36346642],
       [0.07843202, 0.48625455]])

In [35]:
np.random.randn(3,2)
#includes negative numbers

array([[-0.40766535,  1.87474555],
       [ 0.3044422 ,  0.98781856],
       [-0.36353186, -1.19455229]])

In [34]:
np.random.randint(34,100)
#gives randon integer number b/w 34(inclusive) and 100(exclusive)

43

In [37]:
np.random.randint(20,56,100)
#starts from 20 goes upto 55(56 not inclusive) and 100 is the size

array([52, 43, 32, 42, 33, 42, 45, 20, 34, 50, 53, 50, 53, 54, 52, 45, 24,
       38, 40, 44, 53, 23, 38, 50, 22, 43, 48, 32, 34, 47, 49, 55, 29, 35,
       24, 27, 51, 20, 44, 28, 43, 35, 29, 50, 26, 50, 54, 31, 32, 41, 55,
       39, 20, 37, 51, 40, 50, 26, 39, 29, 29, 47, 36, 53, 28, 31, 32, 43,
       21, 34, 38, 28, 40, 36, 52, 36, 52, 52, 31, 32, 52, 20, 43, 46, 51,
       54, 40, 23, 26, 39, 38, 54, 49, 48, 53, 23, 50, 33, 53, 42])

In [38]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
rand_array=np.random.randint(0,100,20)
rand_array
#starts from 0 goes upto 99 and the size of the array is 20 elements

array([60, 95,  7, 22, 76, 98, 23, 73, 99, 52, 41, 64,  2, 90, 41, 78, 88,
       13, 33, 65])

In [41]:
sample_array.reshape(5,6)
#converts the already made array into 5 rows and 6 columns given that the rows*column=number of elements in the already made array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
sample_array.reshape(4,7)
#4*7=28 but we  hae 30 elements in sample_array

<class 'ValueError'>: cannot reshape array of size 30 into shape (4,7)

In [45]:
rand_array.min()
#gives the minimum number in the array already made above
#similarly for max, .max

2

In [48]:
rand_array.argmin()
#gives the index of 2 (that is the index of min value 0,1,2,..(index counting starts from0))
#arg.max() for max

12

In [49]:
#define a array
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
a.T
#Transpose .T stands for transpose of matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
a=np.random.rand(2,3)
a


array([[0.15262908, 0.45663487, 0.4096916 ],
       [0.58438798, 0.96400961, 0.74863439]])

In [54]:
a.T
#makes 3 rows and column

array([[0.15262908, 0.58438798],
       [0.45663487, 0.96400961],
       [0.4096916 , 0.74863439]])

In [55]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
sample_array[-3]

18

In [58]:
sample_array[3:7]
#7th index element is EXCLUSIVE

array([13, 14, 15, 16])

In [59]:
sample_array[1:4]=100
sample_array #mutable

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [60]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[:]=1001  #all elements will changee
subset_sample_array

In [ ]:
#TWO DIMENSIONAL ARRAY

In [ ]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix